spring.datasource.driver-class-name=org.postgresql.Driver
spring.application.name=Moments
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://database:5432/db
spring.datasource.username=postgres
spring.datasource.password=postgres123
SECRET_KEY= lQzy/pq5NQFnoG19M85zeeJrJm+VlI5eyHA4CDNLrrL61Q11K0l7pZKjV3GwI26ixz/kxOsUgzjMpOPGAMUR2tLbh2utpS5ir242Vf28wGipofxrYQerpHpyompvH9ikAMaMOVKSBLVEQO9iEYxFbkekN8mRgnvnVM+kYeJmgjpzpzlrDAsgaQIgXI9kEySgCVmWFpXyl356CpwzEfDBsxaDUXyRjNPLaltIP1Jsy5GVsUuquCsp0rPo8qD9jCRK3onPFQPqWItNajV+CajJTWvDhjy/skh9PYpBZrlMj7RdsyuFko0o/m8oAeNUUZ4oLxJ6HozOcJMGuJLJFeGhK0yTDRzzpkOieNpXdehwv4s=
